In [1]:
import beta_glu
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

/Users/ryanjang123/opt/anaconda3/lib/python3.9/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  warnings.warn(


In [2]:
import pandas as pd
import numpy as np

import pandascharm as pc
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import OneHotEncoder
from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import blosum as bl
from Bio.SubsMat.MatrixInfo import blosum62 as blosum
from Bio import AlignIO
from Bio import SeqIO
from Bio.Align.Applications import MuscleCommandline
from Bio.Align import AlignInfo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Lasso
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_excel('Review Paper Data Final.xlsx')

In [4]:
output = 'pNP-Glc kcat (1/s)'
encoding = 'One-Hot-Encoder'

In [5]:
check = beta_glu.ml_process(encoding, output, df, key = None)

In [6]:
check

Output                          Algorithm  Encoding Method  \
0  pNP-Glc kcat (1/s)                  Linear Regression  One-Hot-Encoder   
1  pNP-Glc kcat (1/s)                   LASSO Regression  One-Hot-Encoder   
2  pNP-Glc kcat (1/s)               Partial Least Square  One-Hot-Encoder   
3  pNP-Glc kcat (1/s)           Decision Tree Regression  One-Hot-Encoder   
4  pNP-Glc kcat (1/s)           Random Forest Regression  One-Hot-Encoder   
5  pNP-Glc kcat (1/s)  Support Vector Machine Regression  One-Hot-Encoder   
6  pNP-Glc kcat (1/s)          Neural Network Regression  One-Hot-Encoder   
7  pNP-Glc kcat (1/s)         Elastic Network Regression  One-Hot-Encoder   

   Code  RMSE Training  RMSE Test  R^2 train  R^2 pred  
0   NaN      20.610301  46.204812   0.947843 -0.048261  
1   NaN      59.635534  48.669512   0.563326 -0.163079  
2   NaN      82.335002  55.027097   0.167630 -0.486786  
3   NaN      20.610301  45.923127   0.947843 -0.035519  
4   NaN      39.314731  45.729307   0.810217 -0.026797  
5   NaN      54.301259  47.132395   0.637951 -0.090773  
6   NaN     102.707979  48.722265  -0.295257 -0.165602  
7   NaN      89.372994  54.854720   0.019246 -0.477485

In [7]:
X,y = beta_glu.encode(encoding, output, df)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [9]:
def SVM(X_train, y_train, X_test):
    param_grid = {'C': [100],
              'epsilon': [0.5],
              'kernel': ['poly']}
 
    grid = GridSearchCV(SVR(), param_grid, refit = True)
    grid.fit(X_train, y_train)
    SVM_pred = grid.predict(X_test)
    pred_training= grid.predict(X_train)
    return SVM_pred, pred_training

In [10]:
DT_pred , DT_train = SVM(X_train, y_train, X_test)

In [11]:
DT_pred

array([33.86710779, 33.86710779, 33.86710779, 33.86710779, 33.86710779,
       33.86710779, 33.86710779, 33.86710779, 33.86710779, 33.86710779,
       33.86710779, 33.86710779, 33.86710779, 33.86710779, 33.86710779,
       33.86710779, 33.86710779, 33.86710779, 33.86710779, 33.86710779,
       33.86710779, 33.86710779, 33.86710779, 33.86710779,  3.72991271,
       33.86710779, 33.86710779, 33.86710779, 33.86710779, 33.86710779,
       33.86710779])

In [12]:
param_list = {"hidden_layer_sizes": [(1,),(50,)], "activation": ["identity", "logistic", "tanh", "relu"], "solver": ["lbfgs", "sgd", "adam"], "alpha": [0.00005,0.0005]}

In [13]:
def EN(X_train, y_train, X_test):
    param_grid = dict()
    param_grid['alpha'] = [1.0]
    param_grid['l1_ratio'] =[0.5]

    grid = GridSearchCV(ElasticNet(), param_grid,scoring='r2', refit = True)
    grid.fit(X_train, y_train)
    EN_pred = grid.predict(X_test)
    pred_training= grid.predict(X_train)

    return EN_pred, pred_training

In [14]:
pred , train = EN(X_train, y_train, X_test)

In [15]:
pred

array([50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112, 50.50940112, 50.50940112, 50.50940112, 50.50940112,
       50.50940112])

In [16]:
print(ElasticNet().get_params()['alpha'])

1.0


In [17]:
import xgboost as xgb

In [24]:
def XGBR(X_train, y_train, X_test):
    params = { 'max_depth': [4],
           'n_estimators': [100],
           'colsample_bytree': [0.2],
           'min_child_weight': [3],
           'gamma': [0.3],
           'subsample': [0.4]}
    model = xgb.XGBRegressor()
    grid = GridSearchCV(estimator=XGBRegressor(), 
                       param_grid=params)
    grid.fit(X_train, y_train)
    XGB_pred = grid.predict(X_test)
    pred_training= grid.predict(X_train)
    return XGB_pred, pred_training

In [25]:
pred , train = XGBR(X_train, y_train, X_test)

In [ ]:
params = { 'max_depth': [4],
           'n_estimators': [100],
           'colsample_bytree': [0.2],
           'min_child_weight': [3],
           'gamma': [0.3],
           'subsample': [0.4]}
model = xgb.XGBRegressor()
grid = GridSearchCV(estimator=XGBRegressor(), 
                   param_grid=params)
grid.fit(X_train, y_train)
XGB_pred = grid.predict(X_test)
pred_training= grid.predict(X_train)

In [ ]:
pred

In [20]:
from xgboost import XGBRegressor

In [22]:
params = { 'max_depth': [4],
           'n_estimators': [100],
           'colsample_bytree': [0.2],
           'min_child_weight': [3],
           'gamma': [0.3],
           'subsample': [0.4]}
model = XGBRegressor()
grid = GridSearchCV(estimator=XGBRegressor(), 
                   param_grid=params)
grid.fit(X_train, y_train)
XGB_pred = grid.predict(X_test)
pred_training= grid.predict(X_train)

In [26]:
pred

array([57.148853, 57.148853, 57.148853, 57.148853, 57.148853, 57.148853,
       57.148853, 57.148853, 57.148853, 57.148853, 57.148853, 57.148853,
       57.148853, 57.148853, 57.148853, 57.148853, 57.148853, 57.148853,
       57.148853, 57.148853, 57.148853, 57.148853, 57.148853, 57.148853,
       57.148853, 57.148853, 57.148853, 57.148853, 57.148853, 57.148853,
       57.148853], dtype=float32)