In [1]:
import beta_glu
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

/Users/ryanjang123/opt/anaconda3/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/Users/ryanjang123/opt/anaconda3/lib/python3.9/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  warnings.warn(


In [2]:
import pandas as pd
import numpy as np

import pandascharm as pc
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import OneHotEncoder
from Bio import SeqIO
from Bio.SeqUtils.ProtParam import ProteinAnalysis
import blosum as bl
from Bio.SubsMat.MatrixInfo import blosum62 as blosum
from Bio import AlignIO
from Bio import SeqIO
from Bio.Align.Applications import MuscleCommandline
from Bio.Align import AlignInfo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale 
from sklearn import model_selection
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import Lasso
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_excel('../beta-glucosidase/data/KcatKm w_ Temperatures.xlsx')

In [4]:
df

Organism Name Actual Organism Name  Temperature Optimum  \
0    AcidothermusCellulolyticus             E1                 70.0   
1    AcidothermusCellulolyticus             E2                 70.0   
2    AcidothermusCellulolyticus             E3                 70.0   
3    AcidothermusCellulolyticus             E4                 70.0   
4    AcidothermusCellulolyticus             E5                 70.0   
..                           ...           ...                  ...   
600             WeissellaCibaria          E605                 45.0   
601             WeissellaCibaria          E606                 45.0   
602             WeissellaCibaria          E607                 45.0   
603             WeissellaCibaria          E608                 45.0   
604             WeissellaCibaria          E609                 45.0   

     Reaction Temperature  Percentage Activity Depending on Optimum Temp  \
0                    70.0                                           1.00   
1                    30.0                                           0.10   
2                    40.0                                           0.20   
3                    50.0                                           0.30   
4                    60.0                                           0.60   
..                    ...                                            ...   
600                  35.0                                           0.71   
601                  40.0                                           0.93   
602                  50.0                                           0.82   
603                  55.0                                           0.39   
604                  60.0                                           0.25   

     pNP-Glc Km (mM)  pnp-glc Vmax pnp-glcVmax units  pNP-Glc kcat (1/s)  \
0               0.37          95.0          umol/min               26.64   
1                NaN           NaN               NaN                 NaN   
2                NaN           NaN               NaN                 NaN   
3                NaN           NaN               NaN                 NaN   
4                NaN           NaN               NaN                 NaN   
..               ...           ...               ...                 ...   
600              NaN           NaN               NaN                 NaN   
601              NaN           NaN               NaN                 NaN   
602              NaN           NaN               NaN                 NaN   
603              NaN           NaN               NaN                 NaN   
604              NaN           NaN               NaN                 NaN   

     pNP-Glc kcat/Km (1/smM)  ...  Cellobiose kcat (1/s)  \
0                  72.000000  ...                    NaN   
1                   7.200000  ...                    NaN   
2                  14.400000  ...                    NaN   
3                  21.600000  ...                    NaN   
4                  43.200000  ...                    NaN   
..                       ...  ...                    ...   
600                 5.382995  ...                    NaN   
601                 7.050965  ...                    NaN   
602                 6.216980  ...                    NaN   
603                 2.956856  ...                    NaN   
604                 1.895421  ...                    NaN   

     Cellobiose kcat/Km (1/smM) pNP-Glc Type of Inhibition  pNP-Glc IC50 (mM)  \
0                           NaN                        NaN                NaN   
1                           NaN                        NaN                NaN   
2                           NaN                        NaN                NaN   
3                           NaN                        NaN                NaN   
4                           NaN                        NaN                NaN   
..                          ...                        ...                ...   
600                         NaN              

In [5]:
output = 'pNP-Glc kcat/Km (1/smM)'
encoding = 'One-Hot-Encoder'
aln = '../beta-glucosidase/data/seqs.aln'

In [6]:
check = beta_glu.ml_process(encoding, output, df, aln, key = None)

In [7]:
X,y = beta_glu.encode(encoding,output,df, aln)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [8]:
a,b = beta_glu.XGBR(X_train,y_train, X_test)

In [9]:
b

array([ 51.109756  ,  78.9714    ,  24.212532  ,  78.9714    ,
       339.81183   ,  78.9714    , 339.81183   ,  14.420506  ,
        78.9714    , 220.63933   ,  71.00497   ,  78.9714    ,
        31.172935  ,  -0.60140705,  78.9714    ,  -1.8299928 ,
         4.6546946 , 186.5667    ,  78.9714    , 199.52022   ,
        78.9714    , 339.81183   ,  78.9714    ,   3.0284004 ,
        85.46479   , 388.35913   ,  65.36444   , 339.81183   ,
        78.9714    ,  14.420506  , 469.82703   , 299.18405   ,
        78.9714    ,  78.9714    ,  99.15186   , 280.22537   ,
       280.22537   ,  78.9714    , 124.76599   ,  78.9714    ,
        13.707228  , 299.18405   ,  13.476635  ,  13.476635  ,
       199.52022   ,  78.9714    ,  65.93916   ,  13.476635  ,
        78.9714    ,  65.36444   ,  44.059303  ,  78.9714    ,
       129.97263   ,  44.059303  ,  64.73579   ,  99.15186   ,
       415.0822    ,  -0.60140705,  31.172935  ,  78.9714    ,
        -2.8017688 ,  42.63291   ,  70.94345   ,  78.97

In [10]:
output = 'pNP-Glc kcat/Km (1/smM)'
encoding = 'Bag-of-Words'
aln = '../beta-glucosidase/data/KcatKm w_ Temperatures.aln'

In [11]:
X,y = beta_glu.encode_temp(encoding, output, df, aln, key = None)

In [12]:
X

array([[53.,  3., 37., ..., 14., 22., 70.],
       [53.,  3., 37., ..., 14., 22., 30.],
       [53.,  3., 37., ..., 14., 22., 40.],
       ...,
       [38.,  0., 35., ..., 18., 23., 50.],
       [38.,  0., 35., ..., 18., 23., 55.],
       [38.,  0., 35., ..., 18., 23., 60.]])

In [13]:
ClustalAlign = AlignIO.read(aln, 'clustal')
summary_align = AlignInfo.SummaryInfo(ClustalAlign )

dframe = pc.from_bioalignment(ClustalAlign)
dframe = dframe.replace('U', '-')
dframe = dframe.replace('O','-')

In [14]:
dframe

E42 E43 E44 E45 E46 E47 E48 E49 E50 E76  ... E106 E104 E103 E102 E101  \
0      -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
1      -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
2      -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
3      -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
4      -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
1306   -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
1307   -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
1308   -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
1309   -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   
1310   -   -   -   -   -   -   -   -   -   -  ...    -    -    -    -    -   

     E100 E220 E116 E119 E584  
0       -    -    -    -    -  
1       -    -    -    -    -  
2       -    -    -    -    -  
3       -    -    -    -    -  
4       -    -    -    -    -  
...   ...  ...  ...  ...  ...  
1306    -    -    -    -    -  
1307    -    -    -    -    -  
1308    -    -    -    -    -  
1309    -    -    -    -    -  
1310    -    -    -    -    -  

[1311 rows x 591 columns]

In [15]:
holder = np.nan
temp1=dframe.transpose()
temp2 = df[['Organism Name',output]]
temp3 =removeoutlier_col(temp2,output).set_index('Organism Name')
Z=pd.concat([temp1, temp3], axis=1).dropna()

NameError: name 'removeoutlier_col' is not defined

In [ ]:
holder = np.nan
temperature = 'Reaction Temperature'
temp1=dframe.transpose()
temp2 = df[['Organism Name',temperature,output]]
temp3 =removeoutlier_col(temp2,output).set_index('Organism Name')
Z=pd.concat([temp1, temp3], axis=1).dropna()

In [ ]:
X=Z.loc[:, Z.columns != output ]

In [ ]:
temp_col = X.loc[:, X.columns == temperature ]

In [ ]:
X = X.loc[:, X.columns != temperature ]

In [ ]:
n = len(X)
enc_seq = np.zeros((n,n))

i = 0

for a in list(X.index):
    j = 0
    for b in list(X.index):
#         enc_seq[i,j] = sum(score_pairwise(X.loc[a], X.loc[b], blosum, -5, -1))
        enc_seq[i,j] = sum(beta_glu.score_pairwise(X.loc[a], X.loc[b], blosum, -5, -1))
        j += 1
    i += 1

X = enc_seq

In [ ]:
X

In [ ]:
temp_col = np.array(temp_col).reshape(-1,1)

In [ ]:
temp_col

In [ ]:
X = np.concatenate((X,temp_col), axis =1)

In [ ]:
encoding = 'BLOSUM62'

In [ ]:
X, y = beta_glu.encode_temp(encoding, output, df, aln, key = None)

In [16]:
X

array([[53.,  3., 37., ..., 14., 22., 70.],
       [53.,  3., 37., ..., 14., 22., 30.],
       [53.,  3., 37., ..., 14., 22., 40.],
       ...,
       [38.,  0., 35., ..., 18., 23., 50.],
       [38.,  0., 35., ..., 18., 23., 55.],
       [38.,  0., 35., ..., 18., 23., 60.]])

In [17]:
y

0      72.000000
1       7.200000
2      14.400000
3      21.600000
4      43.200000
         ...    
600     5.382995
601     7.050965
602     6.216980
603     2.956856
604     1.895421
Name: pNP-Glc kcat/Km (1/smM), Length: 503, dtype: float64